name: build-deploy-pages
on:
  push:
    branches: [ master ]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "10.15.3"
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Render page
        run: npm run render
      - name: Deploy to GH Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./